---
chdir: "/home/andrici/public_html/sybilai"
environment: production
timeout: 30
log: "/home/andrici/public_html/sybilai/log/thin.log"
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
socket: unix:///tmp/sybilai.sock
daemonize: true
